// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232_PE_FA25_LeVoBaoDuy.Data;

#nullable disable

namespace PRN232_PE_FA25_LeVoBaoDuy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251113161411_InitMovies")]
    partial class InitMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232_PE_FA25_LeVoBaoDuy.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PosterImage")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 13, 16, 14, 11, 0, DateTimeKind.Utc),
                            Genre = "Sci-Fi",
                            PosterImage = "https://picsum.photos/seed/matrix/400/600",
                            Rating = 5,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 13, 16, 14, 11, 0, DateTimeKind.Utc),
                            Genre = "Sci-Fi",
                            PosterImage = "https://picsum.photos/seed/inception/400/600",
                            Rating = 5,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 13, 16, 14, 11, 0, DateTimeKind.Utc),
                            Genre = "Action",
                            PosterImage = "https://picsum.photos/seed/darkknight/400/600",
                            Rating = 5,
                            Title = "The Dark Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}

